version: '3.8'

services:
  api:
    build: 
      context: ./services/api
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_DEBUG=0
      - DATABASE_URL=postgresql://PG_USER:PG_PASSWORD@db:5432/phonetrack-server
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
      - DISTANCE_THRESHOLD=500
      - TIME_THRESHOLD=900
    depends_on:
      - db
  db:
    image: postgis/postgis:16-3.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=PG_USER
      - POSTGRES_PASSWORD=PG_PASSWORD
      - POSTGRES_DB=phonetrack-server
  nginx:
    build: ./services/nginx
    volumes:
      - ./services/nginx/allow-list.conf:/etc/nginx/conf.d/allow-list.conf
    ports:
      - 8080:80
    depends_on:
      - api

volumes:
  postgres_data: